import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"]});

export const metadata = {
  title: "Job Board AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{baseTheme: "dark"}}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header/>
          <main className="min-h-screen">{children}</main>
          <footer className="bg-muted/20 py-8">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p className="font-extrabold text-xl">Made with 💗 by{' '}
                <a href="https://github.com/shreyansh-21" target="_blank" rel="noopener noreferrer" className="inline-block text-cyan-400 border-b-2 border-transparent hover:border-cyan-400 hover:translate-x-2 hover:-translate-y-2 transition duration-200 ease-in-out">Shreyansh↗</a></p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
