import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job Board AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-screen">{children}</main>
          <footer className="bg-muted/50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p className="font-extrabold text-xl">Made with 💗 by{' '}
                <a href="https://github.com/shreyansh-21" target="_blank" rel="noopener noreferrer" className="inline-block text-cyan-400 border-b-2 border-transparent hover:border-cyan-400 hover:scale-110 transition duration-300 ease-in-out">Shreyansh↗</a></p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
